from python:3.10-alpine

WORKDIR /home
COPY app_async.py fastapi.requirements.txt .
RUN pip install --no-cache-dir -r fastapi.requirements.txt
CMD exec uvicorn --host 0.0.0.0 --port 80 --workers 18 app_async:app